spring.datasource.url=jdbc:postgresql://localhost:5432/flagr_db
spring.datasource.username=flagr_user
spring.datasource.password=flagr_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
